site_name: Modulinhalte Informatik
nav:
    - Home: index.md
    - Allgemeine Informationen: 
      - Umgang mit KI-/LLM-Tools: allgemein/umgang-ki.md
      - Umgang mit VMs: allgemein/umgang-vm.md
    - Grundlagen:
      - Markdown: grundlagen/markdown.md
      - Git: grundlagen/git.md
    - Webentwicklung:
      - HTTP: webentwicklung/http.md
    - DevOps:
      - Allgemein: devops/allgemein.md
      - Docker/Cloud: devops/docker-cloud.md


theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon-32x32.png  
  language: de
  palette: 
    # Palette toggle for light mode
    - primary: custom
      accent: custom
      scheme: default
      #accent: lime
      #primary: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - primary: custom
      accent: custom
      scheme: slate
      #accent: lime
      #primary: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
  features:
#    - navigation.tabs
    - navigation.footer
    - navigation.instant
  extra:
    generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
copyright: Copyright &copy; 2024 <a href='https://www.gbssg.ch'><span style='font-weight:1000'>gbs</span>sg.ch</a> <span class='green'>|</span> Zusatzunterlagen Informatik <span class='green'>
repo_url: https://github.com/oliverlux/docs

